// <auto-generated />
using System;
using ArshinGroup.DAL.SqlServer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArshinGroup.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArshinGroup.Domain.Models.Abstractions.BaseEntities.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Abstractions.BaseEntities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("discriminator");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<string>("ChinaPrice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("china_price");

                    b.Property<string>("ContentEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_en");

                    b.Property<string>("ContentRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_ru");

                    b.Property<string>("ContentZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_zh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_ru");

                    b.Property<string>("DescriptionZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_zh");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_currency");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("product_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ProductCategoryId")
                        .HasDatabaseName("ix_products_product_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product_categories");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.ProductDeliveryMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_delivery_methods");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_delivery_methods_product_id");

                    b.ToTable("product_delivery_methods", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_product_images");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_images_product_id");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.ProductScpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Lable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lable");

                    b.Property<int>("Languege")
                        .HasColumnType("integer")
                        .HasColumnName("languege");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_variants_product_id");

                    b.ToTable("product_variants", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Services.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_service_categories");

                    b.ToTable("service_categories", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Services.ServiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_en");

                    b.Property<string>("ContentRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_ru");

                    b.Property<string>("ContentZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_zh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_ru");

                    b.Property<string>("DescriptionZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_zh");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_currency");

                    b.Property<int?>("ServiceCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("service_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("ServiceCategoryId")
                        .HasDatabaseName("ix_services_service_category_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Services.ServiceFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Languege")
                        .HasColumnType("integer")
                        .HasColumnName("languege");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_service_features");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_features_service_id");

                    b.ToTable("service_features", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Settings.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonTextEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("button_text_en");

                    b.Property<string>("ButtonTextRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("button_text_ru");

                    b.Property<string>("ButtonTextZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("button_text_zh");

                    b.Property<string>("ButtonUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("button_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("SubTitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub_title_en");

                    b.Property<string>("SubTitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub_title_ru");

                    b.Property<string>("SubTitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub_title_zh");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_banners");

                    b.ToTable("banners", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Settings.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_en");

                    b.Property<string>("AddressRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_ru");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("MapLAT")
                        .HasColumnType("integer")
                        .HasColumnName("map_lat");

                    b.Property<int>("MapLNG")
                        .HasColumnType("integer")
                        .HasColumnName("map_lng");

                    b.Property<string>("OfficeNameEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("office_name_en");

                    b.Property<string>("OfficeNameRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("office_name_ru");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkingHoursRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("working_hours_ru");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Settings.NavigationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int?>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int?>("ParrentId")
                        .HasColumnType("integer")
                        .HasColumnName("parrent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_navigation_items");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_navigation_items_menu_id");

                    b.HasIndex("ParrentId")
                        .HasDatabaseName("ix_navigation_items_parrent_id");

                    b.ToTable("navigation_items", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Settings.NavigationMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_navigation_menus");

                    b.ToTable("navigation_menus", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Settings.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_en");

                    b.Property<string>("ContentRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_ru");

                    b.Property<string>("ContentZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_zh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExcprtpEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excprtp_en");

                    b.Property<string>("ExcprtpRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excprtp_ru");

                    b.Property<string>("ExcprtpZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("excprtp_zh");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_news_items");

                    b.ToTable("news_items", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Settings.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Solutions.Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("ContentEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_en");

                    b.Property<string>("ContentRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_ru");

                    b.Property<string>("ContentZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_zh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_ru");

                    b.Property<string>("DescriptionZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_zh");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price_currency");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleRU")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_ru");

                    b.Property<string>("TitleZH")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_zh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_solutions");

                    b.ToTable("solutions", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Solutions.SolutionFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Languege")
                        .HasColumnType("integer")
                        .HasColumnName("languege");

                    b.Property<int?>("SolutionId")
                        .HasColumnType("integer")
                        .HasColumnName("solution_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_solution_features");

                    b.HasIndex("SolutionId")
                        .HasDatabaseName("ix_solution_features_solution_id");

                    b.ToTable("solution_features", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Solutions.SolutionProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChinaPrice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("china_price");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("SolutionId")
                        .HasColumnType("integer")
                        .HasColumnName("solution_id");

                    b.Property<string>("SortOrder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_solution_products");

                    b.HasIndex("SolutionId")
                        .HasDatabaseName("ix_solution_products_solution_id");

                    b.ToTable("solution_products", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Users.ContactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_contact_request");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_contact_request_user_id");

                    b.ToTable("contact_request", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Users.User", b =>
                {
                    b.HasBaseType("ArshinGroup.Domain.Models.Abstractions.BaseEntities.ApplicationUser");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.Product", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Products.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_products_product_categories_product_category_id");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.ProductDeliveryMethod", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Products.Product", "Product")
                        .WithMany("ProductDeliveryMethods")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_product_delivery_methods_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.ProductImage", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Products.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_product_images_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.ProductScpec", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Products.Product", "Product")
                        .WithMany("ProductScpecs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_product_variants_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Services.ServiceEntity", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Services.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_services_service_categories_service_category_id");

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Services.ServiceFeature", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Services.ServiceEntity", "ServiceEntity")
                        .WithMany("ServiceFeatures")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_service_features_services_service_id");

                    b.Navigation("ServiceEntity");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Settings.NavigationItem", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Settings.NavigationMenu", "NavigationMenu")
                        .WithMany("NavigationItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_navigation_items_navigation_menus_menu_id");

                    b.HasOne("ArshinGroup.Domain.Models.Entities.Settings.NavigationItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParrentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_navigation_items_navigation_items_parrent_id");

                    b.Navigation("NavigationMenu");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Solutions.SolutionFeature", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Solutions.Solution", "Solution")
                        .WithMany("Features")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_solution_features_solutions_solution_id");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Solutions.SolutionProduct", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Solutions.Solution", "Solution")
                        .WithMany("SolutionProducts")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_solution_products_solutions_solution_id");

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Users.ContactRequest", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Entities.Users.User", "User")
                        .WithMany("ContactRequests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_contact_request_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Abstractions.BaseEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Abstractions.BaseEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Abstractions.BaseEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Abstractions.BaseEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("ArshinGroup.Domain.Models.Abstractions.BaseEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ArshinGroup.Domain.Models.Abstractions.BaseEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.Product", b =>
                {
                    b.Navigation("ProductDeliveryMethods");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductScpecs");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Products.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Services.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Services.ServiceEntity", b =>
                {
                    b.Navigation("ServiceFeatures");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Settings.NavigationItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Settings.NavigationMenu", b =>
                {
                    b.Navigation("NavigationItems");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Solutions.Solution", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("SolutionProducts");
                });

            modelBuilder.Entity("ArshinGroup.Domain.Models.Entities.Users.User", b =>
                {
                    b.Navigation("ContactRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
